In [1]:
import numpy as np

In [2]:
arr=np.random.randn(5,4)

In [3]:
arr

array([[ 1.06897112, -0.49737321,  1.74947114, -1.11169784],
       [ 1.43868989, -0.86355875,  0.10966278,  0.51976885],
       [-0.79809601, -0.95083243,  1.39098932, -1.87783427],
       [-0.121415  , -0.09633292,  1.54482819,  1.22293878],
       [ 0.00867441, -0.10452143,  0.19763503, -0.72083555]])

In [5]:
arr.sum(axis=0)

array([ 1.59682442, -2.51261874,  4.99258646, -1.96766003])

In [8]:
arr.sum(axis=1)

array([ 1.20937122,  1.20456277, -2.23577339,  2.55001905, -0.61904755])

In [9]:
np.sort(arr)

array([[-1.11169784, -0.49737321,  1.06897112,  1.74947114],
       [-0.86355875,  0.10966278,  0.51976885,  1.43868989],
       [-1.87783427, -0.95083243, -0.79809601,  1.39098932],
       [-0.121415  , -0.09633292,  1.22293878,  1.54482819],
       [-0.72083555, -0.10452143,  0.00867441,  0.19763503]])

In [10]:
arr

array([[ 1.06897112, -0.49737321,  1.74947114, -1.11169784],
       [ 1.43868989, -0.86355875,  0.10966278,  0.51976885],
       [-0.79809601, -0.95083243,  1.39098932, -1.87783427],
       [-0.121415  , -0.09633292,  1.54482819,  1.22293878],
       [ 0.00867441, -0.10452143,  0.19763503, -0.72083555]])

In [11]:
arr.sort()

In [12]:
arr

array([[-1.11169784, -0.49737321,  1.06897112,  1.74947114],
       [-0.86355875,  0.10966278,  0.51976885,  1.43868989],
       [-1.87783427, -0.95083243, -0.79809601,  1.39098932],
       [-0.121415  , -0.09633292,  1.22293878,  1.54482819],
       [-0.72083555, -0.10452143,  0.00867441,  0.19763503]])

In [13]:
arr.sort(0)

In [14]:
arr

array([[-1.87783427, -0.95083243, -0.79809601,  0.19763503],
       [-1.11169784, -0.49737321,  0.00867441,  1.39098932],
       [-0.86355875, -0.10452143,  0.51976885,  1.43868989],
       [-0.72083555, -0.09633292,  1.06897112,  1.54482819],
       [-0.121415  ,  0.10966278,  1.22293878,  1.74947114]])