# 5 numpy.array方法

In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


## 5.1 求和

In [2]:
a = array([[1,2,3], 
           [4,5,6]])

求所有元素的和：

In [3]:
sum(a)

21

指定求和的维度：

沿着第一维求和：（行）--可以理解为对每一列求和

In [4]:
sum(a, axis=0)

array([5, 7, 9])

沿着第二维求和：

In [5]:
sum(a, axis=1)

array([ 6, 15])

沿着最后一维求和：

In [6]:
sum(a, axis=-1)

array([ 6, 15])

或者使用 `sum` 方法：

In [7]:
a.sum()

21

In [8]:
a.sum(axis=0)

array([5, 7, 9])

In [9]:
a.sum(axis=-1)

array([ 6, 15])

## 5.2 求积

求所有元素的乘积：

In [10]:
a.prod()

720

或者使用函数形式：

In [11]:
prod(a, axis=0)

array([ 4, 10, 18])

## 5.3 求最大最小值

In [3]:
from numpy.random import rand
a = rand(3, 4)
%precision 3
a

array([[  3.880e-01,   8.259e-01,   2.689e-01,   3.782e-04],
       [  8.157e-01,   4.586e-01,   5.074e-02,   4.952e-01],
       [  9.703e-01,   5.821e-01,   1.313e-01,   9.595e-02]])

全局最小：

In [4]:
a.min()

0.000

沿着某个轴的最小：

In [5]:
a.min(axis=0)

array([  3.880e-01,   4.586e-01,   5.074e-02,   3.782e-04])

全局最大：

In [4]:
a.max()

0.913

沿着某个轴的最大：

In [5]:
a.max(axis=-1)

array([ 0.844,  0.469,  0.913])

## 5.4 最大最小值的位置

使用 `argmin, argmax` 方法：

In [6]:
a.argmin()

6

In [7]:
a.argmin(axis=0)

array([1, 1, 1, 1], dtype=int64)

## 5.5 均值

可以使用 `mean` 方法：

In [19]:
a = array([[1,2,3],[4,5,6]])

In [20]:
a.mean()

3.500

In [21]:
a.mean(axis=-1)

array([ 2.,  5.])

也可以使用 `mean` 函数：

In [22]:
mean(a)

3.500

还可以使用 `average` 函数：

In [23]:
average(a, axis = 0)

array([ 2.5,  3.5,  4.5])

`average` 函数还支持加权平均：

In [24]:
average(a, axis = 0, weights=[1,2])

array([ 3.,  4.,  5.])

## 5.6 标准差

用 `std` 方法计算标准差：

In [25]:
a.std(axis=1)

array([ 0.816,  0.816])

用 `var` 方法计算方差：

In [26]:
a.var(axis=1)

array([ 0.667,  0.667])

或者使用函数：

In [27]:
var(a, axis=1)

array([ 0.667,  0.667])

In [28]:
std(a, axis=1)

array([ 0.816,  0.816])

## 5.7 clip 方法

将数值限制在某个范围：

In [27]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

小于3的变成3，大于5的变成5。

## 5.8 ptp 方法

计算最大值和最小值之差：

In [29]:
a.ptp(axis=1)

array([2, 2])

In [30]:
a.ptp()

5

## 5.9 round 方法

近似，默认到整数：

In [10]:
a = array([1.35, 2.5, 1.6])

这里，.5的近似规则为近似到偶数值，可以参考：

https://en.wikipedia.org/wiki/Rounding#Round_half_to_odd

In [32]:
a.round()

array([ 1.,  2.,  2.])

近似到一位小数：

In [33]:
a.round(decimals=1)

array([ 1.4,  2.5,  1.5])